echo "$USER"
echo "$USER haha"
echo "$USER!haha"
echo "$USER#haha"
echo "$USER$haha"
echo "$USER%haha"
echo "$USER&haha"
echo "$USER'haha"
echo "$USER(haha"
echo "$USER)haha"
echo "$USER*haha"
echo "$USER+haha"
echo "$USER,haha"
echo "$USER-haha"
echo "$USER.haha"
echo "$USER/haha"
echo "$USER:haha"
echo "$USER;haha"
echo "$USER<haha"
echo "$USER=haha"
echo "$USER>haha"
echo "$USER?haha"
echo "$USER@haha"
echo "$USER[haha"
echo "$USER\haha"
echo "$USER]haha"
echo "$USER^haha"
echo "$USER{haha"
echo "$USER|haha"
echo "$USER}haha"
echo "$USER~haha"

# echo "$USERéhaha"

