echo "$USER"
echo "$USER haha"
echo "$USER!haha"
echo "$USER#haha"
echo "$USER$haha"
echo "$USER%haha"
echo "$USER&haha"
echo "$USER'haha"
echo "$USER(haha"
echo "$USER)haha"
echo "$USER*haha"
echo "$USER+haha"
echo "$USER,haha"
echo "$USER-haha"
echo "$USER.haha"
echo "$USER/haha"
echo "$USER:haha"
echo "$USER;haha"
echo "$USER<haha"
echo "$USER=haha"
echo "$USER>haha"
echo "$USER?haha"
echo "$USER@haha"
echo "$USER[haha"
echo "$USER\haha"
echo "$USER]haha"
echo "$USER^haha"
echo "$USER{haha"
echo "$USER|haha"
echo "$USER}haha"
echo "$USER~haha"

echo $USER
echo $USER haha
echo $USER!haha
echo $USER#haha
echo $USER$haha
echo $USER%haha
echo $USER'haha'
echo $USER*haha
echo $USER+haha
echo $USER,haha
echo $USER-haha
echo $USER.haha
echo $USER/haha
echo $USER:haha
echo $USER=haha
echo $USER?haha
echo $USER@haha
echo $USER[haha
echo $USER]haha
echo $USER^haha
echo $USER{haha
echo $USER}haha
echo $USER~haha

echo "$"
echo "$ haha"
echo "$%haha"
echo "$&haha"
echo "$'haha"
echo "$)haha"
echo "$*haha"
echo "$+haha"
echo "$,haha"
echo "$.haha"
echo "$/haha"
echo "$:haha"
echo "$;haha"
echo "$<haha"
echo "$=haha"
echo "$>haha"
echo "$?haha"
echo "$\haha"
echo "$]haha"
echo "$^haha"
echo "$|haha"
echo "$}haha"
echo "$~haha"

echo $
echo $ haha
echo $%haha
echo $'haha'
echo $*haha
echo $+haha
echo $,haha
echo $.haha
echo $/haha
echo $:haha
echo $=haha
echo $?haha
echo $]haha
echo $^haha
echo $}haha
echo $~haha

echo "$nothing"
echo "$nothing haha"
echo "$nothing%haha"
echo "$nothing&haha"
echo "$nothing'haha"
echo "$nothing)haha"
echo "$nothing*haha"
echo "$nothing+haha"
echo "$nothing,haha"
echo "$nothing.haha"
echo "$nothing/haha"
echo "$nothing:haha"
echo "$nothing;haha"
echo "$nothing<haha"
echo "$nothing=haha"
echo "$nothing>haha"
echo "$nothing?haha"
echo "$nothing\haha"
echo "$nothing]haha"
echo "$nothing^haha"
echo "$nothing|haha"
echo "$nothing}haha"
echo "$nothing~haha"

echo $nothing
echo $nothing haha
echo $nothing%haha
echo $nothing'haha'
echo $nothing*haha
echo $nothing+haha
echo $nothing,haha
echo $nothing.haha
echo $nothing/haha
echo $nothing:haha
echo $nothing=haha
echo $nothing?haha
echo $nothing]haha
echo $nothing^haha
echo $nothing}haha
echo $nothing~haha